[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.102.3"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

[[redirects]]
  from = "https://www.geogecolab.org/lab-wiki/hipergator-intro-guide"
  to = "https://wiki.geogecolab.org/docs/computers-and-programming/hipergator-intro-guide"
  status = 301
  force = true

[[redirects]]
  from = "https://www.geogecolab.org/lab-wiki/hipergator-intro-guide/hipergator-intro-guide"
  to = "https://wiki.geogecolab.org/docs/computers-and-programming/hipergator-intro-guide"
  status = 301
  force = true

[[redirects]]
  from = "https://www.geogecolab.org/lab-wiki/hipergator-reference-guide"
  to = "https://wiki.geogecolab.org/docs/computers-and-programming/hipergator-reference"
  status = 301
  force = true

[[redirects]]
  from = "https://www.geogecolab.org/lab-wiki/hipergator-reference-guide/hipergator-reference-guide"
  to = "https://wiki.geogecolab.org/docs/computers-and-programming/hipergator-reference"
  status = 301
  force = true

[[redirects]]
  from = "https://www.geogecolab.org/lab-wiki/way-of-geogecolab"
  to = "https://wiki.geogecolab.org/docs/lab-policy-procedures/way-of-geogecolab"
  status = 301
  force = true

[[redirects]]
  from = "https://www.geogecolab.org/lab-wiki/code-of-conduct"
  to = "https://wiki.geogecolab.org/docs/lab-policy-procedures/code-of-conduct"
  status = 301
  force = true
